### PR TITLE
thundergod desktop notifications

### PR DESCRIPTION
**Pull request by flavorjones**
Do you like calling down the thunder? Are you on a linux machine? Are you running a desktop that is compliant with the [Desktop Notifications Specification](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html)? Is your name Mike?

Then you'll love this one quick trick to make Paul Dix Thundergod appear in your desktop notifications.

---

If you have `notify-send` installed, it'll get called when the sweet sweet thunder is called down.

image

### CODE REVIEW

**Comment by pauldix** [comment]
I, for one, approve of this magnificent PR. :shipit:

**Comment by smtlaissezfaire** [comment]
hahahahaha.  

Funny enough, we were using the deploy sounds at LearnUp for the long time.  I had to explain to everyone who you were @pauldix.

It was especially alarming if you'd deploy but forgot that your speakers were on, especially if at a coffee shop.

CC @pariser

**Comment by nodanaonlyzuul** [comment]
Wow! This repo!

This repo has a lot of sweet and tender memories in it. It's README is in textile for one.
I'm surprised and touched the repo lives on in this age of CI/CD pipelines.
I'm going to run your branch on my Ubuntu machine tomorrow.

Your PR has invigorated me to give this repo some much needed attention.
And this PR actually lays some of the groundwork for other improvements.

1.  Thank you.
2.  Stay tuned.
3.  Be good to yourself.

**Comment by nodanaonlyzuul** [comment]
Hey @flavorjones 

Boy oh boy I have about 1,000 ideas to modernize this app. Thanks for the inspiration.

PXL_20201003_235920069

**Pull request merged**
